<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Confirm</strong> deleting conversation' => '<strong>Poista/strong> keskustelu',
    '<strong>Confirm</strong> leaving conversation' => '<strong>Poistu</strong> keskustelusta',
    '<strong>Confirm</strong> message deletion' => '<strong>Vahvista</strong> viestin poistaminen',
    'Add user' => 'Lisää käyttäjä',
    'Delete conversation' => 'Poista keskustelu',
    'Do you really want to delete this conversation?' => 'Haluatko varmasti poistaa tämän keskustelun?',
    'Do you really want to delete this message?' => 'Haluatko varmasti poistaa tämän viestin?',
    'Do you really want to leave this conversation?' => 'Haluatko varmasti poistua tästä keskustelusta?',
    'Leave' => 'Poistu',
    'Leave conversation' => 'Poistu keskustelusta',
    'Leave discussion' => 'Poistu keskustelusta',
    'Send' => 'Lähetä',
    'There are no messages yet.' => 'Täällä ei ole viestejä vielä.',
    'Write an answer...' => 'Kirjoita vastaus...',
    'Cancel' => 'Poistu',
    'Delete' => 'Poista',
];
