<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Delete conversation' => '',
    'Leave conversation' => '',
    '<strong>Confirm</strong> deleting conversation' => '<strong>Confermi</strong> l\'eliminazione della conversazione?',
    '<strong>Confirm</strong> leaving conversation' => '<strong>Confermi</strong> di lasciare la conversazione?',
    '<strong>Confirm</strong> message deletion' => '<strong>Confermi</strong> l\'eliminazione del messaggio?',
    'Add user' => 'Aggiungi utente',
    'Cancel' => 'Annulla',
    'Delete' => 'Cancella',
    'Do you really want to delete this conversation?' => 'Vuoi eliminare questa conversazione?',
    'Do you really want to delete this message?' => 'Vuoi eliminare questo messaggio?',
    'Do you really want to leave this conversation?' => 'Vuoi abbandonare questa conversazione?',
    'Leave' => 'Lascia',
    'Leave discussion' => 'Abbandona la discussione',
    'Send' => 'Invia',
    'There are no messages yet.' => 'Non ci sono messaggi.',
    'Write an answer...' => 'Rispondi...',
];
