<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Write new message' => 'Написать новое сообщение',
    '<strong>Confirm</strong> deleting conversation' => '<strong>Подтвердите</strong> удаление переписки',
    '<strong>Confirm</strong> leaving conversation' => '<strong>Подтвердите</strong> выход из переписки',
    '<strong>Confirm</strong> message deletion' => '<strong>Подтвердите</strong> удаление сообщения',
    'Add user' => 'Добавить пользователя',
    'Cancel' => 'Отменить',
    'Delete' => 'Удалить',
    'Do you really want to delete this conversation?' => 'Вы действительно хотите удалить эту переписку?',
    'Do you really want to delete this message?' => 'Вы действительно хотите удалить это сообщение?',
    'Do you really want to leave this conversation?' => 'Вы действительно хотите покинуть эту переписку?',
    'Leave' => 'Покинуть',
    'Leave discussion' => 'Покинуть переписку',
    'Send' => 'Отправить',
    'There are no messages yet.' => 'Здесь пока нет сообщений.',
    'Write an answer...' => 'Написать ответ ...',
];
