<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Conversation' => '',
    'Receive Notifications when someone opens a new conversation.' => '',
    'Receive Notifications when someone sends you a message.' => '',
    'Allow others to send you private messages' => 'Permitir que otros le envíen mensajes privados',
    'Created At' => 'Creado en',
    'Created By' => 'Creado por',
    'Is Originator' => 'Es Originario',
    'Last Viewed' => 'Visto por última vez',
    'Message' => 'Mensaje',
    'Messages' => 'Mensajes',
    'Receive private messages' => 'Recibir mensajes privados',
    'Title' => 'Titulo',
    'Updated At' => 'Actualizado en',
    'Updated By' => 'Actualizado por',
    'User' => 'Usuario',
];
