<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Write new message' => '@@Escribir nuevo mensaje@@',
    '<strong>Confirm</strong> deleting conversation' => '<strong>Confirmar</strong> eliminación de la conversación',
    '<strong>Confirm</strong> leaving conversation' => '<strong>Confirmar</strong> salida de la conversación',
    '<strong>Confirm</strong> message deletion' => '<strong>Confirmar</strong> eliminación del mensaje',
    'Add user' => 'Añadir usuario',
    'Cancel' => 'Cancelar',
    'Delete' => 'Eliminar',
    'Do you really want to delete this conversation?' => '¿Seguro que quieres eliminar esta conversación?',
    'Do you really want to delete this message?' => '¿Seguro que quieres eliminar este mensaje?',
    'Do you really want to leave this conversation?' => '¿Seguro que quieres abandonar esta conversación?',
    'Leave' => 'Abandonar',
    'Leave discussion' => 'Dejar discusión',
    'Send' => 'Enviar',
    'There are no messages yet.' => 'No hay mensajes aún.',
    'Write an answer...' => 'Escribe una respuesta...',
];
