<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Delete conversation' => '',
    'Leave conversation' => '',
    '<strong>Confirm</strong> deleting conversation' => '<strong>Patvirtinti</strong> pokalbio pašalinimą',
    '<strong>Confirm</strong> leaving conversation' => '<strong>Patvirtinti</strong> išėjimą iš pokalbio',
    '<strong>Confirm</strong> message deletion' => '<strong>Patvirtinti</strong> žinutės pašalinimą',
    'Add user' => 'Pridėti vartotoją',
    'Cancel' => 'Atšaukti',
    'Delete' => 'Ištrinti',
    'Do you really want to delete this conversation?' => 'Ar tikrai norite ištrinti šį pokalbį?',
    'Do you really want to delete this message?' => 'Ar tikrai norite ištrinti šią žinutę?',
    'Do you really want to leave this conversation?' => 'Ar tikrai norite palikti šį pokalbį?',
    'Leave' => 'Palikti',
    'Leave discussion' => 'Išeiti iš pokalbio',
    'Send' => 'Siųsti',
    'There are no messages yet.' => 'Kol kas nėra žinučių.',
    'Write an answer...' => 'Atsakyti...',
];
