<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Write new message' => '@@Yeni bir mesaj yaz@@',
    '<strong>Confirm</strong> deleting conversation' => '<strong>Konuşmayı</strong> sil',
    '<strong>Confirm</strong> leaving conversation' => '<strong>Konuşmadan</strong> ayrıl',
    '<strong>Confirm</strong> message deletion' => '<strong>Mesajı</strong> sil',
    'Add user' => 'Kullanıcı ekle',
    'Cancel' => 'İptal',
    'Delete' => 'Sil',
    'Do you really want to delete this conversation?' => 'Konuşmayı silmek istiyor musun?',
    'Do you really want to delete this message?' => 'Mesajı silmek istiyor musun?',
    'Do you really want to leave this conversation?' => 'Konuşmadan ayrılmak istiyor musun?',
    'Leave' => 'Ayrıl',
    'Leave discussion' => 'Tartışmadan ayrıl',
    'Send' => 'Gönder',
    'There are no messages yet.' => 'Henüz mesaj bulunmuyor.',
    'Write an answer...' => 'Bir cevap yaz',
];
