<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Write new message' => '@@Escrever nova mensagem@@',
    '<strong>Confirm</strong> deleting conversation' => '<strong>Confirmar</strong> apagar conversa',
    '<strong>Confirm</strong> leaving conversation' => '<strong>Confirmar</strong> deixar conversa',
    '<strong>Confirm</strong> message deletion' => '<strong>Confirmar</strong> apagar mensagem',
    'Add user' => 'Adicionar usuário',
    'Cancel' => 'Cancelar',
    'Delete' => 'Apagar',
    'Do you really want to delete this conversation?' => 'Você quer realmente apagar esta conversa?',
    'Do you really want to delete this message?' => 'Você realmente quer apagar esta mensagem?',
    'Do you really want to leave this conversation?' => 'Você quer realmente sair desta conversa?',
    'Leave' => 'Sair',
    'Leave discussion' => 'Deixar discussão',
    'Send' => 'Enviar',
    'There are no messages yet.' => 'Não há mensagens ainda.',
    'Write an answer...' => 'Escreva uma resposta ...',
];
