<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  '<strong>New</strong> message' => '',
  'Copyright © 2013 by humhub' => '@@Copyright © 2013 by humhub.@@',
  'Email preferences' => '@@电子邮件偏好@@',
  'New message' => '@@新消息@@',
  'Reply now' => '现在回复',
  'send you a new message:' => '发送给你一个新消息:',
);
