<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Confirm</strong> deleting conversation' => '确认<strong>删除讨论</strong>',
    '<strong>Confirm</strong> leaving conversation' => '确认<strong>退出讨论</strong>',
    '<strong>Confirm</strong> message deletion' => '确认<strong>删除消息</strong>',
    'Delete conversation' => '删除讨论',
    'Do you really want to delete this conversation?' => '你真的要删除此讨论？',
    'Do you really want to delete this message?' => '你真的要删除此消息？',
    'Do you really want to leave this conversation?' => '你真的要退出此讨论？',
    'Leave' => '退出',
    'Leave conversation' => '退出讨论',
    'Write an answer...' => '回复...',
    'Add user' => '添加用户',
    'Cancel' => '取消',
    'Delete' => '删除',
    'Leave discussion' => '退出讨论',
    'Send' => '发送',
    'There are no messages yet.' => '还没有消息.',
];
