<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Allow users to start new conversations' => '',
    'Start new conversations' => '',
    'Allow others to send you private messages' => 'Sta anderen toe om u privéberichten te sturen',
    'Conversation' => 'Gesprek',
    'Created At' => 'Gemaakt op',
    'Created By' => 'Gemaakt door',
    'Is Originator' => 'Is bedenker',
    'Last Viewed' => 'Laatst weergegeven',
    'Message' => 'Bericht',
    'Messages' => 'Berichten',
    'Receive Notifications when someone opens a new conversation.' => 'Meldingen ontvangen wanneer iemand een nieuw gesprek opent.',
    'Receive Notifications when someone sends you a message.' => 'Ontvang meldingen wanneer iemand u een bericht stuurt.',
    'Receive private messages' => 'Ontvang privéberichten',
    'Title' => 'Titel',
    'Updated At' => 'Bijgewerkt op',
    'Updated By' => 'Bijgewerkt door',
    'User' => 'Gebruiker',
];
