<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Confirm</strong> deleting conversation' => '',
    '<strong>Confirm</strong> leaving conversation' => '',
    '<strong>Confirm</strong> message deletion' => '',
    'Do you really want to delete this conversation?' => '',
    'Do you really want to delete this message?' => '',
    'Do you really want to leave this conversation?' => '',
    'Leave' => '',
    'Write new message' => '@@Schrijf nieuw bericht@@',
    'Add user' => 'Gebruiker toevoegen',
    'Cancel' => 'Annuleren',
    'Delete' => 'Verwijder',
    'Leave discussion' => 'Verlaat discussie',
    'Send' => 'Versturen',
    'There are no messages yet.' => 'Er zijn nog geen berichten.',
    'Write an answer...' => 'Schrijf antwoord...',
];
