<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Write new message' => '@@Schreibe eine neue Nachricht@@',
    '<strong>Confirm</strong> deleting conversation' => '<strong>Bestätige</strong> Löschung der Konversation',
    '<strong>Confirm</strong> leaving conversation' => '<strong>Bestatige</strong> verlassen der Konversation',
    '<strong>Confirm</strong> message deletion' => '<strong>Bestätige</strong> Löschung der Nachricht ',
    'Add user' => 'Füge Empfänger hinzu',
    'Cancel' => 'Abbrechen',
    'Delete' => 'Löschen',
    'Do you really want to delete this conversation?' => 'Willst du diese Konversation wirklich löschen?',
    'Do you really want to delete this message?' => 'Willst du dies Nachricht wirklich löschen?',
    'Do you really want to leave this conversation?' => 'Willst du die Unterhaltung wirklich verlassen?',
    'Leave' => 'Verlassen',
    'Leave discussion' => 'Verlasse die Diskussion',
    'Send' => 'Senden',
    'There are no messages yet.' => 'Aktuell keine Nachrichten vorhanden.',
    'Write an answer...' => 'Schreibe eine Antwort ...',
];
