<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Write new message' => '@@نوشتن پیغام جدید@@',
    '<strong>Confirm</strong> deleting conversation' => '<strong>تایید</strong> حذف مکالمه',
    '<strong>Confirm</strong> leaving conversation' => '<strong>تایید</strong>  ترک مکالمه',
    '<strong>Confirm</strong> message deletion' => '<strong>تایید</strong>  حذف پیغام',
    'Add user' => 'اضافه کردن کاربر',
    'Cancel' => 'انصراف',
    'Delete' => 'حذف',
    'Do you really want to delete this conversation?' => 'آیا واقعا می‌خواهید این مکالمه را حذف کنید؟',
    'Do you really want to delete this message?' => 'آیا واقعا می‌خواهید این پیغام را حذف کنید؟',
    'Do you really want to leave this conversation?' => 'آیا واقعا می‌خواهید این مکالمه را ترک کنید؟',
    'Leave' => 'ترک',
    'Leave discussion' => 'ترک گفت‌وگو',
    'Send' => 'ارسال',
    'There are no messages yet.' => 'هنوز هیچ پیغامی وجود ندارد.',
    'Write an answer...' => 'نوشتن پاسخ . . .',
];
