<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
  '<strong>Confirm</strong> deleting conversation' => '<strong> 真的嗎？ </strong> 刪除對話',
  '<strong>Confirm</strong> leaving conversation' => '<strong> 真的嗎？ </strong> 離開對話',
  '<strong>Confirm</strong> message deletion' => '<strong> 真的嗎？ </strong> 刪除訊息',
  'Add user' => '加其他人',
  'Cancel' => '取消',
  'Delete' => '刪除',
  'Delete conversation' => '',
  'Do you really want to delete this conversation?' => '你確定要刪除這串對話嗎？',
  'Do you really want to delete this message?' => '你確定要刪除這個訊息嗎？',
  'Do you really want to leave this conversation?' => '你確定要離開這串對話嗎？',
  'Leave' => '離開',
  'Leave discussion' => '',
  'Leave conversation' => '',
  'Send' => '發送',
  'There are no messages yet.' => '沒有任何訊息',
  'Write an answer...' => '寫點回覆',
  'Write new message' => '寫點新訊息',
];
