<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Conversation' => '',
    'Receive Notifications when someone opens a new conversation.' => '',
    'Receive Notifications when someone sends you a message.' => '',
    'Allow others to send you private messages' => 'Cho phép người khác gửi bạn thư riêng',
    'Created At' => 'Tạo lúc',
    'Created By' => 'Tạo bởi',
    'Is Originator' => 'Là người khởi phát',
    'Last Viewed' => 'Xem lần cuối',
    'Message' => 'Tin nhắn',
    'Messages' => 'Tin nhắn',
    'Receive private messages' => 'Nhận tin nhắn riêng tư ',
    'Title' => 'Tiêu đề',
    'Updated At' => 'Cập nhật lúc',
    'Updated By' => 'Cập nhật bởi',
    'User' => 'User',
];
