<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Write new message' => '@@Skriv ny besked@@',
    '<strong>Confirm</strong> deleting conversation' => '<strong>Bekræft</strong> sletning af samtale',
    '<strong>Confirm</strong> leaving conversation' => '<strong>Bekræft</strong> afslutning af samtale',
    '<strong>Confirm</strong> message deletion' => '<strong>Bekræft</strong> sletning af besked',
    'Add user' => 'Tilføj bruger',
    'Cancel' => 'Afbryd',
    'Delete' => 'Slet',
    'Do you really want to delete this conversation?' => 'Vil du virkelig gerne slette denne samtale?',
    'Do you really want to delete this message?' => 'Vil du virkelig gerne slette denne besked?',
    'Do you really want to leave this conversation?' => 'Vil du virkelig gerne forlade denne samtale',
    'Leave' => 'Forlad',
    'Leave discussion' => 'Forlad diskussion',
    'Send' => 'Send',
    'There are no messages yet.' => 'Der er ingen beskeder endnu.',
    'Write an answer...' => 'Skriv et svar...',
];
