name: Codeception Tests - min version

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * 1"


jobs:
  tests:
    uses: humhub/module-coding-standards/.github/workflows/codeception-min-version.yml@main
    with:
      module-id: mail
      use-rest-module: true
