name: PHP CS Fixer

on:
  push:
    branches:
      - master
      - main
      - develop
    paths:
      - '**.php'
  schedule:
    - cron: "0 0 * * 0"

jobs:
  fixers:
    uses: humhub/actions/.github/workflows/module-php-cs-fixer.yml@main
