name: PHP Codeception Tests - min version

on:
  push:
  workflow_dispatch:  
  schedule:
    - cron: "0 0 * * 0"

jobs:
  tests:
    uses: humhub/actions/.github/workflows/module-tests-min-version.yml@main
    with:
      module-id: mail
      use-rest-module: true
